name: Build WDA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build WebDriverAgentRunner
        run: |
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./build \
            CODE_SIGNING_ALLOWED=NO

      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -r ./build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WebDriverAgentRunner.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner-ipa
          path: WebDriverAgentRunner.ipa
